# Question 1
Consider the following Python module:
a = 0
def b():
global a
a = c(a)
def c(a):
return a + 2
After importing the module into the interpreter, you execute:
>>> b()
>>> b()
>>> b()
>>> a
?
What value is displayed when the last expression (a) is evaluated? Explain your
answer by indicating what happens in every executed statement.

In [1]:
# Define the initial value of the variable
initial_value = 0

# Define the first function to modify the global variable
def modify_global():
    global initial_value
    initial_value = add_two(initial_value)

# Define the second function to add two to the input value
def add_two(x):
    return x + 2

# Execute the modify_global function three times
modify_global()
modify_global()
modify_global()

# Output the value of 'initial_value'
initial_value

6

# Question 2
Function fileLength(), given to you, takes the name of a file as input and returns
the length of the file
ts)):
>>> fileLength('midterm.py')
284
>>> fileLength('idterm.py')
Traceback (most recent call last):
File "<pyshell#34>", line 1, in <module>
fileLength('idterm.py')
File "/Users/me/midterm.py", line 3, in fileLength
infile = open(filename)
FileNotFoundError: [Errno 2] No such file or directory:
'idterm.py'
As shown above, if the file cannot be found by the interpreter or if it cannot be read
as a text file, an exception will be raised. Modify function fileLength() so that a
friendly message is printed instead:
>>> fileLength('midterm.py')
358
>>> fileLength('idterm.py')
File idterm.py not found.

In [22]:
def file_length(file_name):
    try:
        file = open(file_name, 'r')
        contents = file.read()
        file.close()
        print(len(contents))
    except FileNotFoundError:
        print(f"File '{file_name}' not found.")
    except IOError:
        print(f"Could not read the file '{file_name}'.")
        
# Test with the filename 'Filelength'
file_length('Filelength.txt')

107

# Question 3
Write a class named Marsupial that can be used as shown below:
>>> m = Marsupial()
>>> m.put_in_pouch('doll')
>>> m.put_in_pouch('firetruck')
>>> m.put_in_pouch('kitten')
>>> m.pouch_contents()
['doll', 'firetruck', 'ki
>>> Now write a class named Kangaroo as a subclass of Marsupial that inherits all the
attributes of Marsupial and also:
a. extends the Marsupial __init__ constructor to take, as input, the
coordinates x and y of the Kangaroo object,
b. supports method jump that takes number values dx and dy as input and
moves the kangaroo by dx units along the x-axis and by dy units along the y-
axis, and
c. overloads the __str__ operator so it behaves as shown below.
>>> k = Kangaroo(0,0)
>>> print(k)
I am a Kangaroo located at coordinates (0,0)
>>> k.put_in_pouch('doll')
>>> k.put_in_pouch('firetruck')
>>> k.put_in_pouch('kitten')
>>> k.pouch_contents()
['doll', 'firetruck', 'kitten']
>>> k.jump(1,0)
>>> k.jump(1,0)
>>> k.jump(1,0)
>>> print(k)
I am a Kangaroo located at coordinates (3,0)tten']

In [30]:
class Marsupial:
    def __init__(self):
        self.pouch = []

    def put_in_pouch(self, item):
        self.pouch.append(item)

    def pouch_contents(self):
        return self.pouch


class Kangaroo(Marsupial):
    def __init__(self, x, y):
        super().__init__()
        self.x = x
        self.y = y

    def jump(self, dx, dy):
        self.x += dx
        self.y += dy

    def __str__(self):
        return f"I am a Kangaroo located at coordinates ({self.x},{self.y})"

# Example usage:
k = Kangaroo(0, 0)
print(k)  # I am a Kangaroo located at coordinates (0,0)
k.put_in_pouch('doll')
k.put_in_pouch('firetruck')
k.put_in_pouch('kitten')
print(k.pouch_contents())  # ['doll', 'firetruck', 'kitten']
k.jump(1, 0)
k.jump(1, 0)
k.jump(1, 0)
print(k)  # I am a Kangaroo located at coordinates (3,0)

I am a Kangaroo located at coordinates (0,0)
['doll', 'firetruck', 'kitten']
I am a Kangaroo located at coordinates (3,0)

# Question 4
Write function collatz() that takes a positive integer x as input and prints the
Collatz sequence starting at x. A Collatz sequence is obtained by repeatedly applying
this rule to the previous number x in the sequence:
x = { 𝑥/2 𝑖𝑓 𝑥 𝑖𝑠 𝑒𝑣𝑒𝑛
3𝑥 + 1 𝑖𝑓 𝑥 𝑖𝑠 𝑜𝑑𝑑
Your function should stop when the sequence gets to number 1. Your
implementation must be recursive, without any 
>>> collatz(1)
1
>>> collatz(10)
10
5
16
8
4
2
1loops.

In [42]:
def collatz(x):
    # Print the current number in the sequence
    print(x)
    
    # Base case: if x is 1, stop the recursion
    if x == 1:
        return
    # Recursive case: apply the Collatz rule based on whether x is even or odd
    elif x % 2 == 0:
        collatz(x // 2)
    else:
        collatz(3 * x + 1)

# Test cases
print(">>> collatz(1)")
collatz(1)  # Output: 1
print("\n>>> collatz(10)")
collatz(10)  # Output: 10, 5, 16, 8, 4, 2, 1

>>> collatz(1)
1

>>> collatz(10)
10
5
16
8
4
2
1

# Question 5
Write a recursive method binary() that takes a non-negative
integer n and prints the binary representation of integer n.
>>> binary(0)
0
>>> binary(1)
1
>>> binary(3)
11
>>> binary(9)
1001

In [40]:
def binary(n):
    # Base case: if n is 0 or 1, print n directly
    if n < 2:
        print(n, end='')
    else:
        # Recursive case: divide the number by 2 and call binary on the quotient
        binary(n // 2)
        # After returning from recursion, print the remainder
        print(n % 2, end='')

# example
print(">>> binary(0)")
binary(0)  # Output: 0
print("\n>>> binary(1)")
binary(1)  # Output: 1
print("\n>>> binary(3)")
binary(3)  # Output: 11
print("\n>>> binary(9)")
binary(9)  # Output: 1001

>>> binary(0)
0
>>> binary(1)
1
>>> binary(3)
11
>>> binary(9)
1001

# Question 6
Implement a class named HeadingParser that can be used to parse an HTML
document, and retrieve and print all the headings in the document. You should
implement your class as a subclass of HTMLParser, defined in Standard Library
module html.parser. When fed a string containing HTML code, your class should
print the headings, one per line and in the order in which they appear in the
document. Each heading should be indented as follows: an h1 heading should
indentation 0, and h2 heading should have indentation 1, etc. Test your
implementation using w3c.html.
>>> infile = open('w3c.html')
>>> content = infile.read()
>>> infile.close()
>>> hp = HeadingParser()
>>> hp.feed(content)
W3C Mission
Principles have

In [44]:
from html.parser import HTMLParser

class HeadingParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.in_heading = False
        self.heading_level = 0

    def handle_starttag(self, tag, attrs):
        if tag in ['h1', 'h2', 'h3', 'h4', 'h5', 'h6']:
            self.in_heading = True
            self.heading_level = int(tag[1])  # Extract heading level from tag name

    def handle_endtag(self, tag):
        if tag in ['h1', 'h2', 'h3', 'h4', 'h5', 'h6']:
            self.in_heading = False

    def handle_data(self, data):
        if self.in_heading:
            print(' ' * (self.heading_level - 1) + data)

# Read the HTML file content
with open('w3c.html', 'r', encoding='utf-8') as infile:
    content = infile.read()

# Create an instance of the HeadingParser and feed it the HTML content
hp = HeadingParser()
hp.feed(content)

W3C Mission
 Principles

# Question 7
Implement recursive function webdir() that takes as input: a URL (as a string) and
non-negative integers depth and indent. Your function should visit every web
page reachable from the starting URL web page in depth clicks or less, and print
each web page's URL. As shown below, indentation, specified by indent, should
be used to indicate the depth of a URL.
>>>
webdir('http://reed.cs.depaul.edu/lperkovic/csc242/test1.html'
, 2, 0)
http://reed.cs.depaul.edu/lperkovic/csc242/test1.html
http://reed.cs.depaul.edu/lperkovic/csc242/test2.html
http://reed.cs.depaul.edu/lperkovic/csc242/test4.html
http://reed.cs.depaul.edu/lperkovic/csc242/test3.html
http://reed.cs.depaul.edu/lperkovic/csc242/test4.html

In [61]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

def webdir(url, depth, indent):
    if depth < 0:
        return
    try:
        response = requests.get(url)
        response.raise_for_status()
        print(' ' * indent + url)
        if depth == 0:
            return

        soup = BeautifulSoup(response.text, 'html.parser')
        links = soup.find_all('a', href=True)
        for link in links:
            href = link['href']
            next_url = urljoin(url, href)
            webdir(next_url, depth - 1, indent + 4)
    except requests.RequestException as e:
        print(f"Failed to fetch {url}: {e}")

# Example usage:
webdir('http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/', 2, 0)

http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/
    http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/Ch11.pptx
    http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/ch11.py
    http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/frankenstein.txt
    http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/five.html
        http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/four.html
        http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/one.html
        http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/two.html
    http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/four.html
        http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/five.html
    http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/three.html
        http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/four.html
    http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/links.html
        http://www.google.com
        http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/test.html
Failed to fetch mailto:me@example.net: No connection adapters were found for 'mailto:me@example.net'
    http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/one.html
        http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/two.html
        http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/three.html
    http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/test.html
    http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/two.html
        http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/four.html
    http://reed.cs.depaul.edu/lperkovic/csc242/lecture8/w3c.html
        http://www.w3.org/Consortium/mission.html

# Question 8
Write SQL queries on the below database table that return:
a) All the temperature data.
b) All the cities, but without repetition.
c) All the records for India.
d) All the Fall reco
e) The city, country, and season for which the average rainfall is between 200
and 400 millimeters.
f) The city and country for which the average Fall temperature is above 20
degrees, in increasing temperature order.
g) The total annual rainfall for Cairo.
h) The total rainfall for each season.rds.

In [13]:
import pandas as pd
import sqlite3

# Create a DataFrame
data = {
    'City': ['Mumbai', 'Mumbai', 'Mumbai', 'Mumbai', 'London', 'London', 'London', 'London', 'Cairo', 'Cairo', 'Cairo', 'Cairo'],
    'Country': ['India', 'India', 'India', 'India', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'Egypt', 'Egypt', 'Egypt', 'Egypt'],
    'Season': ['Winter', 'Spring', 'Summer', 'Fall', 'Winter', 'Spring', 'Summer', 'Fall', 'Winter', 'Spring', 'Summer', 'Fall'],
    'Temperature': [24.8, 28.4, 27.9, 27.6, 4.2, 8.3, 15.7, 10.4, 13.6, 20.7, 27.7, 22.2],
    'Rainfall': [5.9, 16.2, 1549.4, 346.0, 207.7, 169.6, 157.0, 218.5, 16.5, 6.5, 0.1, 4.5]
}

df = pd.DataFrame(data)

# Connect to a SQLite database in memory
conn = sqlite3.connect(':memory:')
df.to_sql('weather_data', conn, index=False, if_exists='replace')

# Define a function to execute and display SQL queries
def execute_query(query):
    return pd.read_sql_query(query, conn)

# a) All the temperature data
query_a = "SELECT Temperature FROM weather_data"
print("a) All the temperature data:")
print(execute_query(query_a))

# b) All the cities, but without repetition
query_b = "SELECT DISTINCT City FROM weather_data"
print("\nb) All the cities, but without repetition:")
print(execute_query(query_b))

# c) All the records for India
query_c = "SELECT * FROM weather_data WHERE Country = 'India'"
print("\nc) All the records for India:")
print(execute_query(query_c))

# d) All the Fall records
query_d = "SELECT * FROM weather_data WHERE Season = 'Fall'"
print("\nd) All the Fall records:")
print(execute_query(query_d))

# e) The city, country, and season for which the average rainfall is between 200 and 400 millimeters
query_e = '''
SELECT City, Country, Season
FROM weather_data
GROUP BY City, Country, Season
HAVING AVG(Rainfall) BETWEEN 200 AND 400
'''
print("\ne) The city, country, and season for which the average rainfall is between 200 and 400 millimeters:")
print(execute_query(query_e))

# f) The city and country for which the average Fall temperature is above 20 degrees, in increasing temperature order
query_f = '''
SELECT City, Country
FROM weather_data
WHERE Season = 'Fall'
GROUP BY City, Country
HAVING AVG(Temperature) > 20
ORDER BY AVG(Temperature)
'''
print("\nf) The city and country for which the average Fall temperature is above 20 degrees, in increasing temperature order:")
print(execute_query(query_f))

# g) The total annual rainfall for Cairo
query_g = "SELECT SUM(Rainfall) AS Total_Annual_Rainfall FROM weather_data WHERE City = 'Cairo'"
print("\ng) The total annual rainfall for Cairo:")
print(execute_query(query_g))

# h) The total rainfall for each season
query_h = "SELECT Season, SUM(Rainfall) AS Total_Rainfall FROM weather_data GROUP BY Season"
print("\nh) The total rainfall for each season:")
print(execute_query(query_h))

# Close the connection
conn.close()

a) All the temperature data:
    Temperature
0          24.8
1          28.4
2          27.9
3          27.6
4           4.2
5           8.3
6          15.7
7          10.4
8          13.6
9          20.7
10         27.7
11         22.2

b) All the cities, but without repetition:
     City
0  Mumbai
1  London
2   Cairo

c) All the records for India:
     City Country  Season  Temperature  Rainfall
0  Mumbai   India  Winter         24.8       5.9
1  Mumbai   India  Spring         28.4      16.2
2  Mumbai   India  Summer         27.9    1549.4
3  Mumbai   India    Fall         27.6     346.0

d) All the Fall records:
     City         Country Season  Temperature  Rainfall
0  Mumbai           India   Fall         27.6     346.0
1  London  United Kingdom   Fall         10.4     218.5
2   Cairo           Egypt   Fall         22.2       4.5

e) The city, country, and season for which the average rainfall is between 200 and 400 millimeters:
     City         Country  Season
0  London  United Kingdom    Fall
1  London  United Kingdom  Winter
2  Mumbai           India    Fall

f) The city and country for which the average Fall temperature is above 20 degrees, in increasing temperature order:
     City Country
0   Cairo   Egypt
1  Mumbai   India

g) The total annual rainfall for Cairo:
   Total_Annual_Rainfall
0                   27.6

h) The total rainfall for each season:
   Season  Total_Rainfall
0    Fall           569.0
1  Spring           192.3
2  Summer          1706.5
3  Winter           230.1

# Question 9
. Suppose list words is defined as follows:
>>> words = ['The', 'quick', 'brown', 'fox', 'jumps', 'over',
'the', 'lazy', 'dog']
Write list comprehension expressions that use list words and generate the following
lists:
a) ['THE', 'QUICK', 'BROWN', 'FOX', 'JUMPS', 'OVER', 'THE',
'LAZY', 'DOG']
b) ['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the',
'lazy', 'dog']
c) [3, 5, 5, 3, 5, 4, 3, 4, 3] (the list of lengths of words in list
words).
d) [['THE', 'the', 3], ['QUICK', 'quick', 5], ['BROWN',
'brown', 5], ['FOX', 'fox', 3], ['JUMPS', 'jumps', 5],
['OVER', 'over', 4], ['THE', 'the', 3], ['LAZY', 'lazy',
4], ['DOG', 'dog', 3]] (the list containing a list for every word of list
words, where each list contains the word in uppercase and lowercase and the
length of the word.)
e) ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the',
'lazy', 'dog'] (the list of words in list words containing 4 or more
characters.)

In [15]:
words = ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']

# a) Convert each word to uppercase
uppercase_words_list = [word.upper() for word in words]

# b) Return each word as is (already in lowercase)
lowercase_words_list = [word.lower() for word in words]

# c) Create a list of lengths of each word
lengths_of_words_list = [len(word) for word in words]

# d) Create a list of lists containing the uppercase word, lowercase word, and length of the word
word_details_list = [[word.upper(), word.lower(), len(word)] for word in words]

# e) Filter words with 4 or more characters
longer_words_list = [word for word in words if len(word) >= 4]

# Outputting the results
(uppercase_words_list, lowercase_words_list, lengths_of_words_list, word_details_list, longer_words_list)

(['THE', 'QUICK', 'BROWN', 'FOX', 'JUMPS', 'OVER', 'THE', 'LAZY', 'DOG'],
 ['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog'],
 [3, 5, 5, 3, 5, 4, 3, 4, 3],
 [['THE', 'the', 3],
  ['QUICK', 'quick', 5],
  ['BROWN', 'brown', 5],
  ['FOX', 'fox', 3],
  ['JUMPS', 'jumps', 5],
  ['OVER', 'over', 4],
  ['THE', 'the', 3],
  ['LAZY', 'lazy', 4],
  ['DOG', 'dog', 3]],
 ['quick', 'brown', 'jumps', 'over', 'lazy'])